---
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_REGION'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:

- name: amazon
  driver_plugin: ec2
  driver_config:
    image_id: ami-ee2aa59d
    region: <%= ENV['AWS_REGION'] %>
    availability_zone: <%= ENV['AWS_REGION'] %>a
    instance_type: t2.micro
    iam_profile_name: gocdAgent

suites:
- name: default
  run_list:
  - recipe[core-linux]
  attributes: {}