---
provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:

- name: amazon
  driver_plugin: ec2
  driver_config:
    image_id: ami-ee2aa59d
    region: eu-west-1
    availability_zone: eu-west-1a
    flavor_id: t2.micro
    iam_profile_name: gocdAgent
 
suites:
- name: default
  run_list:
  - recipe[core-linux]
  attributes: {}